        <footer id="footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-sm-push-3 col-xs-12">
                        <div class="text-center">
                            <p class="footer-fineprint">
                                Service provided by <a href="https://www.clarin.eu">CLARIN</a>
                            </p>
                        </div>
                    </div>
                    <div class="col-sm-3 col-sm-pull-6 col-xs-12">
                        <div class="hidden-xs">                            
                        </div>
                        <div class="version-info text-center-xs">
                        </div>
                    </div>
                    <div class="col-sm-3 hidden-xs text-right">
                        <a href="mailto:clarin@clarin.eu">Contact</a>
                    </div>
                    <div class="visible-xs-block text-center">
                        <a disabled="disabled">About</a>
                        &nbsp;<a href="mailto:clarin@clarin.eu">Contact</a>
                    </div>
                </div>
            </div>
        </footer>
</html>
