
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>

<html lang="en-GB" xmlns="http://www.w3.org/1999/xhtml">

    <head>
        <title>CLARIN VLO</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <link rel="stylesheet" href="style/css/bootstrap-clarin.css" type="text/css"/>
        <link rel="stylesheet" href="style/css/clarin-maintenance.css" type="text/css"/>
            
	</head>
    <body>
        <header id="header" role="banner">
            <div class="clarin-top visible-xs">
                <a class="logo center-block" href="http://www.clarin.eu"></a>
            </div>
            <div class="navbar-static-top  navbar-default navbar" role="navigation">
				<div class="container">
					<div class="navbar-header">
					</div>
				</div>
        	</div>
        </header>
